language: node_js
node_js: '10'
cache: yarn
git:
  depth: 3
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
env:
  global:
  - NODE_ENV=test
script: yarn test
deploy:
  provider: heroku
  app: missed-connections-server
  api_key:
    secure: vmpvWZKyczjH/U+lVTvJG13WjQpHbHPfsZP2i5YjThWrbByMt3xwwsYuRa8R7CbmxKZv5JIggLyMHeGO9O4cLmoZY80SARQAKMdGtnTGM2t+uVpK/zPHgMwBcip/pgMJIbH7k1YdxI4qaHPJr4OiZcC/tRWyUbF7XL4UDmD1rp8Pt7LOytS11pzNTtYgrW5xEIguscp7VJbxeB94MCmsS9sJMz7RGrEUQF/alkciofk9DU++qNYL7wpnR0flRDsf4anyEOg1H5spAmSo2da69+td8EqPeqY7j8B443w9a0qOElEJLKnSrtQzgpw5AKG4ILOp9XqFNBYHycen8NFFo0f6zBHVro4l8txD3ngXw5wYTms41fYBiiVe9Ll7q8JpI/OyrCE6sx0k8NdZShsR2oXYVE4maIB16diBUPOABQJMnrPr57biVeLtHgj3NMf0U39YgCJ4obln2vi09yNlo68ZK9Amm/z3muY6wje3c8PzBeEJH8zA7Hc0KvtrmNS/ZQVKABcj6G47XlylcDJ5APd9BSxel1PdDT0IZykaNDFhROXIcyhJqNlAgXXcKrs9as6v4x4KjI5uKIVzNRoPds160HH8zZ30FNtPNTD3uzvghc7NBdwjopEMOg+SJfQ6cbzIW3grSytcArKEYTNduuol3tOZsNtpc4s3z0zLd3k=
after_success: yarn coverage
