language: node_js
node_js: '10'
cache: yarn
git:
  depth: 3
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
env:
  global:
  - NODE_ENV=test
script: yarn test
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
- export PATH="$HOME/.yarn/bin:$PATH"
deploy:
  provider: heroku
  api_key:
    secure: oMO0y5fkOLKrybRZ0HLm4UzmCaSrL8R/5i945AkVGvnTP5W2JQl+OOBgZ14r9bU2WBmg/rz0/ygeBgo1etAnBr6oWR5aQne1DywRfEBgRIHM9MLV94Z4FveqatFMwjG/C++4dSBhpNYGmzXjVQvKHysfTZsSB2wHHmf3r9iYIH6ec0edfux93fZFimtq0uNN2IYwQahnKBJAYy/N3zSQ8WTMe3htOV0cOLMTNfTKegauHpjDPGagHiai+Wpy7NI4DKY7d9lYiEzZLYuypqZfgGVtzTEfWM2tr0+qRo0LhfluTD9s8bkrTiMJmYw7GqTvOY3F86mER3rtqEBeSNLFNiiKkgALquGwqq/1XFfgujmCbxJMRsF+HpGJOOvE5yFV2LR+YG19kUVtK8/KWWmhYNdd31NcgN2w4cOJtMfPL8KxnJuzPOzBCXQHzjaJVxl2er3VPALiHf2UUJYAjY7hPhG6K/724ardC+RXjQuP23aBSXKHV4wUYCb+mF8g/PL7fuR/jb9bfeoVSztxV4GOmnj6+b+S9owZFrPsbWGCG/CUpF+UdgcAVhj/fkfJOpn1MYefgOJdyx+friguY1Y8/asaBKF8r+oOHSepR1U1lH7jXcNmV//obXbUXugnlPN9QvHj96HKjab+XOZtm+uxmhZn1oaeo991XyzdPL8A7IU=
after_success: yarn coverage
