version: "3"
services:
  server:
    build:
      context: .
    image: gkatsanos/server
    environment:
      - MONGO_URI=mongodb://mongodb:27017/isawyou
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  client:
    image: gkatsanos/client
    build: .
    volumes:
      - .:/app
      - /app/node_modules/

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
