version: "3"
services:
  server:
    build: .
    command: yarn test
    environment:
      - MONGO_URI_TESTS=mongodb://mongodb:27017/isawyou-test
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
