version: "3"
services:
  server:
    build: .
    image: gkatsanos/server
    environment:
      - MONGO_URI=mongodb://mongodb:27017/missed-connections
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
