version: "3"
services:
  server:
    build: .
    command: yarn test:debug
    environment:
      - MONGO_URI_TESTS=mongodb://mongodb:27017/missed-connections-test
    depends_on:
      - mongodb
    ports:
      - "9229:9229"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
