version: "3"
services:
  server:
    build: .
    command: yarn test
    environment:
      - PORT
      - MONGO_URI
      - JWT_SECRET
      - JWT_EXPIRATION_MINUTES
      - BASE_URI
      - MONGO_URI_TESTS
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
